// This an example of how not to do things.
{
  tokens = [
      NUM="regexp:\d+"
    ]
}

calcFile ::= item_*

private item_ ::= expr | CRLF

expr ::=  term '+' expr |
          term '-' expr |
          term
term ::= factor '*' term |
         factor '/' term |
         factor
factor ::= NUM | '(' expr ')'