// This an example of how now to do things.
{
  tokens = [
      PLUS = '+'
      MINUS = '-'
      MUL = '*'
      DIV = '/'
      OPEN_B = '('
      CLOSE_B = ')'
      IDENTIFIER="regexp:\p{Alpha}\w*"
      DIGIT="regexp:\d+"
    ]
}

calcFile ::= item_*

private item_ ::= expr | CRLF

expr ::=  term PLUS expr | term
term ::= factor MUL term | factor
factor ::= DIGIT | IDENTIFIER |  OPEN_B expr CLOSE_B