{
  tokens = [
      PLUS = '+'
      MINUS = '-'
      MUL = '*'
      DIV = '/'
      OPEN_B = '('
      CLOSE_B = ')'
      IDENTIFIER="regexp:\p{Alpha}\w*"
      DIGIT="regexp:\d+"
    ]
}

calcFile ::= item_*

private item_ ::= expr | CRLF

expr ::=  add_group | mul_group | primary_group

private add_group ::= add_expr | minus_expr
private mul_group ::= mul_expr | div_expr
private primary_group ::= literal_expr | paren_expr

add_expr ::= expr PLUS expr {extends=expr}
minus_expr ::= expr MINUS expr {extends=expr}
mul_expr ::= expr MUL expr {extends=expr}
div_expr ::= expr DIV expr {extends=expr}
literal_expr ::= DIGIT {extends=expr}
paren_expr ::= OPEN_B expr CLOSE_B {extends=expr}